services:
  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_CONTAINER_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_CONTAINER_DATABASE}
      MYSQL_USER: ${MYSQL_CONTAINER_USER}
      MYSQL_PASSWORD: ${MYSQL_CONTAINER_PASSWORD}
      # MYSQL_INITDB_SKIP_TZINFO: '1'
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
